apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS monitor_logs (
        id SERIAL PRIMARY KEY,
        url VARCHAR(255) NOT NULL,
        status_code INTEGER,
        response_time_ms FLOAT,
        is_up BOOLEAN,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );